### ISSUE TITLE
Validations loosing its focus while typing

### ISSUE THREAD

**Issue by RameshMenta** [enisn/UraniumUI#560] opened 2024-02-01 16:21 UTC
I am following this [page](https://enisn-projects.io/docs/en/uranium/latest/themes/material/Validations) to add `URANIUM UI Validations` for my `MAUI 8.0` project. It displays a `TextField `as expected but while typing the name it is losing its focus.

I created a new project and added the necessary NuGet packages and here is my `XAML `code

```
xmlns:material="http://schemas.enisn-projects.io/dotnet/maui/uraniumui/material"
xmlns:validations="clr-namespace:InputKit.Shared.Validations;assembly=InputKit.Maui"

<material:TextField Title="Enter Name">
    <validations:MinLengthValidation MinLength="3" />
</material:TextField>
```

On typing the first char it displays the error label **"The field should contain at least 3 characters"** and loses its focus on `TextFiled`. I manually need to click on `TextField `and then have to type another char. Now, on typing the third char, it clears the error label and again loses its focus on `TextFiled `so, I now again manually click on `TextFiled `to enter further characters.

I tried with `ValidationBinding `too but I see the same behavior.

`Text="{v:ValidationBinding Form.Email, Mode=TwoWay}"`

```
<PackageReference Include="UraniumUI.Material" Version="2.7.4" />
<PackageReference Include="UraniumUI.Validations.DataAnnotations" Version="2.7.4" />
```

Am I missing something here?

**Comment by DevFromDownUnder** [comment] 2024-02-06 12:11
Duplicate of https://github.com/enisn/UraniumUI/issues/373

Awaiting Microsoft
https://github.com/enisn/UraniumUI/issues/373#issuecomment-1893101551

**Comment by enisn** [comment] 2024-02-23 13:55
This will be tracked in https://github.com/enisn/UraniumUI/issues/373

**Closed as not planned by enisn** 2024-02-23 13:55 UTC
