### ISSUE TITLE
TextField System.Reflection.TargetInvocationException: 'Exception has been thrown by the target of an invocation.'Maui 8.0.91 UraniumUI 2.10.2

### ISSUE THREAD

**Issue by kaniosm** [enisn/UraniumUI#800] opened 2024-10-08 14:46 UTC
This happens after updating from UraniumUI 2.9.1 to UraniumUI 2.10.2.
The problem happens when setting the corner radius over a global style:

<Style TargetType="material:TextField">
     <Setter Property="CornerRadius" Value="20"/>
</Style>

**Comment by enisn** [comment] 2024-10-10 08:49
Same with #801 
Since 801 has more detailed content, I'll close this as duplicate of #801 

Please follow progress in #801

**Closed as not planned by enisn** 2024-10-10 08:49 UTC
