### ISSUE TITLE
Implement - Missing Event in material:TextField - Completed

### ISSUE THREAD

**Issue by Sullivan008** [enisn/UraniumUI#321] opened 2023-05-11 12:30 UTC
I want to achieve the equivalent to the following for material:TextField

```
<Entry Text="Serch Text">
    <Entry.Behaviors>
        <toolkit:EventToCommandBehavior Command="{Binding SearchCommand}" EventName="Completed" />
    </Entry.Behaviors>
</Entry>
```

i.e. I want to react to certain events like Focused, Unfocused, Completed etc. that exist for plain MAUI controls.

I tried this:

```
<material:TextField Title="Search Text" Text="{Binding SearchText}">
    <material:TextField.Behaviors>
        <toolkit:EventToCommandBehavior Command="{Binding SearchCommand}" EventName="Completed" />
    </material:TextField.Behaviors>
</material:TextField>
```

does not work, the event does not existing!

Can you enable the Completed Event on the TextField or do I have to use a different approach?

**Comment by StepKie** [comment] 2023-05-11 12:43
Obvious duplicate of https://github.com/enisn/UraniumUI/issues/263, respectively https://github.com/enisn/UraniumUI/issues/278

A quick search before opening a new issue would have surfaced this

**Comment by enisn** [comment] 2023-05-11 19:22
`ReturnCommand` works as expected for now. So, implementing Completed event is not so prioritized, I'm moving this to backlog with `Good first issue` label.

@Sullivan008 you can try using ReturnCommand of TextField

```xml
<material:TextField Title="Search Text" Text="{Binding SearchText}" ReturnCommand="{Binding SearchCommand}"/>
```

**Comment by StepKie** [comment] 2023-05-11 19:27
@enisn Just trying to understand: why do you move this into the backlog if you don't want to drown in duplicate issues? I would just close it, since it is obviously the same as the issues I linked, I think there should just be one issue for #263, #278 and #321. In my original issue, I event explicitly mentioned the Completed event as well ...

**Comment by enisn** [comment] 2023-05-11 21:44
Unfocused & Focused events were fixed, so I closed other issues for those, this issue can stand for Completed event. 

`Completed` event didn't exist in TextField, so it's a new feature. But using Commands is a better approach, There is an equivalent command to `Completed` event which is `ReturnCommand`, and I worked that command too. It's working well now. So, implementing it as event isn't a mandatory currently. But still PR is welcome for this event.

---

As a short answer, I closed those issues by assuming they're referencing a bug on `Unfocused` & `Focused` events. And I left this issue open because the issue refers to `Completed` event. _(which is currently doesn't exist)_

**Comment by Sullivan008** [comment] 2023-05-22 08:46
Hi @enisn ,

When could you implement the Completed Event? Unfortunately, I would really need it, because the BarCode Scanner - Although it is set to hit Enter during Scann, it does not trigger the Return Command :/

**Comment by enisn** [comment] 2023-05-22 09:02
I want to be far away from events as much as possible. Working with C# events requires careful management due to the challenges associated with event registering and unregistering. Unregistered events can hinder object disposal at runtime.

But, it seems it's a nice feature and we can implement it in the v2.5

**Comment by Sullivan008** [comment] 2023-05-22 09:07
Thanks for your answer @enisn !

I actually want to convert it to Command using the Community - Toolkit and manage it as such.

When is the milestone scheduled or when is the feature scheduled? I'm only asking so I know when to schedule in my code the implementation of the new feature.

**Closed as completed** 2023-05-23 19:08 UTC
Labels: enhancement, good first issue, control-textfield
